server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: resume-analyzer-route
          uri: http://localhost:8083
          predicates:
            - Path=/analyzer/**
          filters:
            - RewritePath=/analyzer/(?<segment>.*), /${segment}

        - id: resume-generator-route
          uri: http://localhost:8082
          predicates:
            - Path=/generator/**
          filters:
            - RewritePath=/generator/(?<segment>.*), /${segment}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      analytics: analytics-topic

